#######################################################################################################################
#                                                                                                                     #
# Copyright (c) 2018 Qualcomm Technologies, Inc.                                                                      #
#                                                                                                                     #
# All rights reserved.                                                                                                #
#                                                                                                                     #
# Redistribution and use in source and binary forms, with or without modification, are permitted (subject to the      #
# limitations in the disclaimer below) provided that the following conditions are met:                                #
# * Redistributions of source code must retain the above copyright notice, this list of conditions and the following  #
#   disclaimer.                                                                                                       #
# * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the         #
#   following disclaimer in the documentation and/or other materials provided with the distribution.                  #
# * Neither the name of Qualcomm Technologies, Inc. nor the names of its contributors may be used to endorse or       #
#   promote products derived from this software without specific prior written permission.                            #
#                                                                                                                     #
# NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED  #
# BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED #
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT      #
# SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR   #
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES LOSS OF USE,      #
# DATA, OR PROFITS OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,      #
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,   #
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.                                                                  #
#                                                                                                                     #
#######################################################################################################################

# dvs global configurations
global:

  # tac length
  TacLength: 8

  # minimum and maximum global imei lengths
  MinImeiLength: 14
  MaxImeiLength: 16

  # minimum and maximum imei range
  MinImeiRange: '000000'
  MaxImeiRange: 1000000

  NoOfThreads: 10
  ImeiBatchSize: 1000

  # variables to be configured
  HelpUrl: 'dirbs.net.pk/help'

  # minimum and maximum file content length
  MinFileContent: 1
  MaxFileContent: 1000000

  # delete older files time
  Time: 24  # time set to 24 hours

  # retry count for bulk process
  Retry: 10

# allowed file extensions
allowed_file_types:
  AllowedTypes: ['text/tab-separated-values', 'text/plain']
  AllowedExt: ['tsv', 'txt']

# application base url
application_base:
  BaseUrl: '/api/v1'
  version: 'v1'

# celery configurations
celery:

  RabbitmqUrl: 'pyamqp://'
  RabbitmqBackend: 'amqp://'

  RedisUrl: 'redis://'
  RedisBackend: 'redis://'

  RpcUrl: 'rpc://'
  RpcBackend: 'rpc://'

  CeleryTasks: ['app.api.v1.helpers.scheduled', 'app.api.v1.helpers.bulk_common']